#! /usr/bin/python
from navigation_mode_switcher_ros.navigation_switcher import NavigationMode
import rospy

if __name__ == '__main__':
  rospy.init_node('navigation_mode_switcher_test', anonymous=True)
  mode = NavigationMode(package = 'mdr_2dslam', route_to_launch_file = 'ros/launch/2dslam.launch')
  mode.start()
  rospy.sleep(10)
  mode.stop()
