#! /usr/bin/python
from navigation_mode_switcher_ros.navigation_switcher import NavigationMode

if __name__ == '__main__':
  mode = NavigationMode(package = 'mdr_2dslam', launch_file = '2dslam.launch')
  mode.start()

  while True:
      pass
 
  mode.shutdown()
